# Generated by Django 6.0.6 on 2026-06-13 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipemodels',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
