# Generated by Django 6.0.6 on 2026-06-16 01:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_recipemodels_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipemodels',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='recipes.category'),
        ),
    ]
