# Generated by Django 6.0.6 on 2026-06-16 02:15

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_recipemodels_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RecipeModels',
            new_name='Recipe',
        ),
    ]
